name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate Pac-Man contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Trim bottom whitespace from SVGs
        run: |
          perl -0777 -pi -e 's/<svg width="(\d+)" height="(\d+)"/"<svg width=\"$1\" height=\"".($2-15)."\""/e' dist/pacman-contribution-graph.svg dist/pacman-contribution-graph-dark.svg

      - name: Push SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}